name: PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  pr-title:
    uses: anton-vylushchak/.github/.github/workflows/pr-title.yaml@v1.0.0
